// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: src/ejemplo/jflex/lexico.flex

/* JFlex example: partial Java language lexer specification */
package ejemplo.jflex;

/**
 * This class is a simple example lexer.
 */

// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class MiLexico {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1, 1
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\1\u0200\1\u0300\1\u0400\1\u0500\1\u0600\1\u0700"+
    "\1\u0800\1\u0900\1\u0a00\1\u0b00\1\u0c00\1\u0d00\1\u0e00\1\u0f00"+
    "\1\u1000\1\u0100\1\u1100\1\u1200\1\u1300\1\u0100\1\u1400\1\u1500"+
    "\1\u1600\1\u1700\1\u1800\1\u1900\1\u1a00\1\u1b00\1\u0100\1\u1c00"+
    "\1\u1d00\1\u1e00\2\u1f00\1\u2000\7\u1f00\1\u2100\1\u2200\1\u2300"+
    "\1\u1f00\1\u2400\1\u2500\2\u1f00\31\u0100\1\u2600\121\u0100\1\u2700"+
    "\4\u0100\1\u2800\1\u0100\1\u2900\1\u2a00\1\u2b00\1\u2c00\1\u2d00"+
    "\1\u2e00\53\u0100\1\u2f00\41\u1f00\1\u0100\1\u3000\1\u3100\1\u0100"+
    "\1\u3200\1\u3300\1\u3400\1\u3500\1\u3600\1\u3700\1\u3800\1\u3900"+
    "\1\u3a00\1\u0100\1\u3b00\1\u3c00\1\u3d00\1\u3e00\1\u3f00\1\u4000"+
    "\1\u4100\1\u1f00\1\u4200\1\u4300\1\u4400\1\u4500\1\u4600\1\u4700"+
    "\1\u4800\1\u4900\1\u4a00\1\u4b00\1\u4c00\1\u4d00\1\u1f00\1\u4e00"+
    "\1\u4f00\1\u5000\1\u1f00\3\u0100\1\u5100\1\u5200\1\u5300\12\u1f00"+
    "\4\u0100\1\u5400\17\u1f00\2\u0100\1\u5500\41\u1f00\2\u0100\1\u5600"+
    "\1\u5700\2\u1f00\1\u5800\1\u5900\27\u0100\1\u5a00\2\u0100\1\u5b00"+
    "\45\u1f00\1\u0100\1\u5c00\1\u5d00\11\u1f00\1\u5e00\24\u1f00\1\u5f00"+
    "\1\u6000\1\u1f00\1\u6100\1\u6200\1\u6300\1\u6400\2\u1f00\1\u6500"+
    "\5\u1f00\1\u6600\1\u6700\1\u6800\5\u1f00\1\u6900\1\u6a00\4\u1f00"+
    "\1\u6b00\2\u1f00\1\u6c00\16\u1f00\246\u0100\1\u6d00\20\u0100\1\u6e00"+
    "\1\u6f00\25\u0100\1\u7000\34\u0100\1\u7100\14\u1f00\2\u0100\1\u7200"+
    "\u0b06\u1f00\1\u2700\u02fe\u1f00";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\0\1\1\1\3\22\0\1\1"+
    "\1\0\1\4\10\0\1\5\4\0\1\6\11\7\3\0"+
    "\1\10\1\0\1\11\1\0\32\12\1\0\1\13\2\0"+
    "\1\12\1\0\1\14\1\15\1\16\1\12\1\17\5\12"+
    "\1\20\1\21\1\12\1\22\1\23\2\12\1\24\1\25"+
    "\1\26\6\12\57\0\1\12\12\0\1\12\4\0\1\12"+
    "\5\0\27\12\1\0\37\12\1\0\u01ca\12\4\0\14\12"+
    "\16\0\5\12\7\0\1\12\1\0\1\12\21\0\165\12"+
    "\1\0\2\12\2\0\4\12\1\0\1\12\6\0\1\12"+
    "\1\0\3\12\1\0\1\12\1\0\24\12\1\0\123\12"+
    "\1\0\213\12\1\0\255\12\1\0\46\12\2\0\1\12"+
    "\6\0\51\12\10\0\55\12\1\0\1\12\1\0\2\12"+
    "\1\0\2\12\1\0\1\12\10\0\33\12\4\0\4\12"+
    "\35\0\13\12\5\0\100\12\12\27\4\0\146\12\1\0"+
    "\10\12\2\0\12\12\1\0\6\12\12\27\3\12\2\0"+
    "\1\12\20\0\73\12\2\0\145\12\16\0\12\27\54\12"+
    "\4\0\1\12\2\0\1\12\2\0\56\12\22\0\34\12"+
    "\4\0\13\12\65\0\25\12\1\0\10\12\25\0\17\12"+
    "\1\0\201\12\2\0\12\27\1\0\23\12\1\0\10\12"+
    "\2\0\2\12\2\0\26\12\1\0\7\12\1\0\1\12"+
    "\3\0\4\12\2\0\11\12\2\0\2\12\2\0\4\12"+
    "\10\0\1\12\4\0\2\12\1\0\5\12\2\0\12\27"+
    "\2\12\12\0\1\12\1\0\1\12\2\0\3\12\1\0"+
    "\6\12\4\0\2\12\2\0\26\12\1\0\7\12\1\0"+
    "\2\12\1\0\2\12\1\0\2\12\2\0\1\12\1\0"+
    "\5\12\4\0\2\12\2\0\3\12\3\0\1\12\7\0"+
    "\4\12\1\0\1\12\7\0\12\27\6\12\13\0\3\12"+
    "\1\0\11\12\1\0\3\12\1\0\26\12\1\0\7\12"+
    "\1\0\2\12\1\0\5\12\2\0\12\12\1\0\3\12"+
    "\1\0\3\12\2\0\1\12\17\0\4\12\2\0\12\27"+
    "\11\0\7\12\1\0\3\12\1\0\10\12\2\0\2\12"+
    "\2\0\26\12\1\0\7\12\1\0\2\12\1\0\5\12"+
    "\2\0\11\12\2\0\2\12\2\0\3\12\10\0\2\12"+
    "\4\0\2\12\1\0\5\12\2\0\12\27\1\0\1\12"+
    "\20\0\2\12\1\0\6\12\3\0\3\12\1\0\4\12"+
    "\3\0\2\12\1\0\1\12\1\0\2\12\3\0\2\12"+
    "\3\0\3\12\3\0\14\12\4\0\5\12\3\0\3\12"+
    "\1\0\4\12\2\0\1\12\6\0\1\12\16\0\12\27"+
    "\20\0\15\12\1\0\3\12\1\0\27\12\1\0\20\12"+
    "\3\0\10\12\1\0\3\12\1\0\4\12\7\0\2\12"+
    "\1\0\3\12\5\0\4\12\2\0\12\27\20\0\4\12"+
    "\1\0\10\12\1\0\3\12\1\0\27\12\1\0\12\12"+
    "\1\0\5\12\2\0\11\12\1\0\3\12\1\0\4\12"+
    "\7\0\2\12\7\0\1\12\1\0\4\12\2\0\12\27"+
    "\1\0\2\12\15\0\4\12\1\0\10\12\1\0\3\12"+
    "\1\0\63\12\1\0\3\12\1\0\5\12\5\0\4\12"+
    "\7\0\5\12\2\0\12\27\12\0\6\12\2\0\2\12"+
    "\1\0\22\12\3\0\30\12\1\0\11\12\1\0\1\12"+
    "\2\0\7\12\3\0\1\12\4\0\6\12\1\0\1\12"+
    "\1\0\10\12\6\0\12\27\2\0\2\12\15\0\72\12"+
    "\5\0\17\12\1\0\12\27\47\0\2\12\1\0\1\12"+
    "\1\0\5\12\1\0\30\12\1\0\1\12\1\0\27\12"+
    "\2\0\5\12\1\0\1\12\1\0\6\12\2\0\12\27"+
    "\2\0\4\12\40\0\1\12\27\0\2\12\6\0\12\27"+
    "\13\0\1\12\1\0\1\12\1\0\1\12\4\0\12\12"+
    "\1\0\44\12\4\0\24\12\1\0\22\12\1\0\44\12"+
    "\11\0\1\12\71\0\100\12\12\27\6\0\100\12\12\27"+
    "\4\12\2\0\46\12\1\0\1\12\5\0\1\12\2\0"+
    "\53\12\1\0\115\12\1\0\4\12\2\0\7\12\1\0"+
    "\1\12\1\0\4\12\2\0\51\12\1\0\4\12\2\0"+
    "\41\12\1\0\4\12\2\0\7\12\1\0\1\12\1\0"+
    "\4\12\2\0\17\12\1\0\71\12\1\0\4\12\2\0"+
    "\103\12\2\0\3\12\40\0\20\12\20\0\126\12\2\0"+
    "\6\12\3\0\u016c\12\2\0\21\12\1\0\32\12\5\0"+
    "\113\12\3\0\13\12\7\0\15\12\1\0\7\12\13\0"+
    "\25\12\13\0\24\12\14\0\15\12\1\0\3\12\1\0"+
    "\2\12\14\0\124\12\3\0\1\12\4\0\2\12\2\0"+
    "\12\27\41\0\3\12\2\0\12\27\6\0\131\12\7\0"+
    "\53\12\5\0\106\12\12\0\37\12\1\0\14\12\4\0"+
    "\14\12\12\0\12\27\36\12\2\0\5\12\13\0\54\12"+
    "\4\0\32\12\6\0\12\27\46\0\34\12\4\0\77\12"+
    "\1\0\35\12\2\0\1\12\12\27\6\0\12\27\15\0"+
    "\1\12\10\0\17\12\101\0\114\12\4\0\12\27\21\0"+
    "\11\12\14\0\60\12\12\27\72\12\14\0\70\12\10\0"+
    "\12\27\3\0\3\12\12\27\44\12\2\0\11\12\7\0"+
    "\53\12\2\0\3\12\20\0\3\12\1\0\47\12\5\0"+
    "\372\12\1\0\33\12\2\0\6\12\2\0\46\12\2\0"+
    "\6\12\2\0\10\12\1\0\1\12\1\0\1\12\1\0"+
    "\1\12\1\0\37\12\2\0\65\12\1\0\7\12\1\0"+
    "\1\12\3\0\3\12\1\0\7\12\3\0\4\12\2\0"+
    "\6\12\4\0\15\12\5\0\3\12\1\0\7\12\102\0"+
    "\2\12\23\0\1\12\34\0\1\12\15\0\1\12\20\0"+
    "\15\12\63\0\41\12\21\0\1\12\4\0\1\12\2\0"+
    "\12\12\1\0\1\12\3\0\5\12\6\0\1\12\1\0"+
    "\1\12\1\0\1\12\1\0\4\12\1\0\13\12\2\0"+
    "\4\12\5\0\5\12\4\0\1\12\21\0\51\12\u022d\0"+
    "\64\12\26\0\57\12\1\0\57\12\1\0\205\12\6\0"+
    "\11\12\14\0\46\12\1\0\1\12\5\0\1\12\2\0"+
    "\70\12\7\0\1\12\17\0\30\12\11\0\7\12\1\0"+
    "\7\12\1\0\7\12\1\0\7\12\1\0\7\12\1\0"+
    "\7\12\1\0\7\12\1\0\7\12\1\0\40\12\57\0"+
    "\1\12\325\0\3\12\31\0\17\12\1\0\5\12\2\0"+
    "\5\12\4\0\126\12\2\0\2\12\2\0\3\12\1\0"+
    "\132\12\1\0\4\12\5\0\53\12\1\0\136\12\21\0"+
    "\33\12\65\0\306\12\112\0\360\12\20\0\215\12\103\0"+
    "\56\12\2\0\15\12\3\0\20\12\12\27\2\12\24\0"+
    "\63\12\1\0\12\12\1\0\163\12\45\0\11\12\2\0"+
    "\147\12\2\0\65\12\2\0\5\12\60\0\61\12\30\0"+
    "\64\12\14\0\106\12\12\0\12\27\6\0\30\12\3\0"+
    "\1\12\1\0\3\12\12\27\44\12\2\0\44\12\14\0"+
    "\35\12\3\0\101\12\16\0\1\12\12\27\6\0\20\12"+
    "\12\27\5\12\1\0\67\12\11\0\16\12\2\0\12\27"+
    "\6\0\27\12\3\0\111\12\30\0\3\12\2\0\20\12"+
    "\2\0\5\12\12\0\6\12\2\0\6\12\2\0\6\12"+
    "\11\0\7\12\1\0\7\12\1\0\53\12\1\0\14\12"+
    "\10\0\173\12\1\0\2\12\2\0\12\27\6\0\244\12"+
    "\14\0\27\12\4\0\61\12\4\0\156\12\2\0\152\12"+
    "\46\0\7\12\14\0\5\12\5\0\14\12\1\0\15\12"+
    "\1\0\5\12\1\0\1\12\1\0\2\12\1\0\2\12"+
    "\1\0\154\12\41\0\153\12\22\0\100\12\2\0\66\12"+
    "\50\0\14\12\4\0\20\12\20\0\20\12\3\0\2\12"+
    "\30\0\3\12\40\0\5\12\1\0\207\12\23\0\12\27"+
    "\7\0\32\12\4\0\1\12\1\0\32\12\13\0\131\12"+
    "\3\0\6\12\2\0\6\12\2\0\6\12\2\0\3\12"+
    "\43\0\14\12\1\0\32\12\1\0\23\12\1\0\2\12"+
    "\1\0\17\12\2\0\16\12\42\0\173\12\105\0\65\12"+
    "\210\0\1\12\202\0\35\12\3\0\61\12\17\0\1\12"+
    "\37\0\40\12\15\0\36\12\5\0\53\12\5\0\36\12"+
    "\2\0\44\12\4\0\10\12\1\0\5\12\52\0\236\12"+
    "\2\0\12\27\6\0\44\12\4\0\44\12\4\0\50\12"+
    "\10\0\64\12\234\0\67\12\11\0\26\12\12\0\10\12"+
    "\230\0\6\12\2\0\1\12\1\0\54\12\1\0\2\12"+
    "\3\0\1\12\2\0\27\12\12\0\27\12\11\0\37\12"+
    "\101\0\23\12\1\0\2\12\12\0\26\12\12\0\32\12"+
    "\106\0\70\12\6\0\2\12\100\0\4\12\1\0\2\12"+
    "\5\0\10\12\1\0\3\12\1\0\35\12\2\0\3\12"+
    "\4\0\1\12\40\0\35\12\3\0\35\12\43\0\10\12"+
    "\1\0\36\12\31\0\66\12\12\0\26\12\12\0\23\12"+
    "\15\0\22\12\156\0\111\12\67\0\63\12\15\0\63\12"+
    "\15\0\50\12\10\0\12\27\306\0\35\12\12\0\1\12"+
    "\10\0\41\12\217\0\27\12\11\0\107\12\37\0\12\27"+
    "\17\0\74\12\25\0\31\12\7\0\12\27\6\0\65\12"+
    "\1\0\12\27\4\0\3\12\11\0\44\12\2\0\1\12"+
    "\11\0\105\12\4\0\4\12\3\0\12\27\1\12\1\0"+
    "\1\12\43\0\22\12\1\0\45\12\6\0\1\12\101\0"+
    "\7\12\1\0\1\12\1\0\4\12\1\0\17\12\1\0"+
    "\12\12\7\0\73\12\5\0\12\27\6\0\4\12\1\0"+
    "\10\12\2\0\2\12\2\0\26\12\1\0\7\12\1\0"+
    "\2\12\1\0\5\12\1\0\12\12\2\0\2\12\2\0"+
    "\3\12\2\0\1\12\6\0\1\12\5\0\7\12\2\0"+
    "\7\12\3\0\5\12\213\0\113\12\5\0\12\27\4\0"+
    "\2\12\40\0\106\12\1\0\1\12\10\0\12\27\246\0"+
    "\66\12\2\0\11\12\27\0\6\12\42\0\101\12\3\0"+
    "\1\12\13\0\12\27\46\0\71\12\7\0\12\27\66\0"+
    "\33\12\2\0\17\12\4\0\12\27\306\0\73\12\145\0"+
    "\100\12\12\27\25\0\1\12\240\0\10\12\2\0\56\12"+
    "\2\0\10\12\1\0\2\12\33\0\77\12\10\0\1\12"+
    "\10\0\112\12\3\0\1\12\42\0\71\12\7\0\11\12"+
    "\1\0\55\12\1\0\11\12\17\0\12\27\30\0\36\12"+
    "\2\0\26\12\1\0\16\12\111\0\7\12\1\0\2\12"+
    "\1\0\54\12\3\0\1\12\1\0\2\12\1\0\11\12"+
    "\10\0\12\27\6\0\6\12\1\0\2\12\1\0\45\12"+
    "\1\0\2\12\1\0\6\12\7\0\12\27\u0136\0\27\12"+
    "\11\0\232\12\146\0\157\12\21\0\304\12\274\0\57\12"+
    "\321\0\107\12\271\0\71\12\7\0\37\12\1\0\12\27"+
    "\146\0\36\12\2\0\5\12\13\0\67\12\11\0\4\12"+
    "\14\0\12\27\11\0\25\12\5\0\23\12\260\0\100\12"+
    "\200\0\113\12\4\0\71\12\7\0\21\12\100\0\2\12"+
    "\1\0\1\12\34\0\370\12\10\0\363\12\15\0\37\12"+
    "\61\0\3\12\21\0\4\12\10\0\u018c\12\4\0\153\12"+
    "\5\0\15\12\3\0\11\12\7\0\12\12\3\0\2\12"+
    "\306\0\5\12\3\0\6\12\10\0\10\12\2\0\7\12"+
    "\36\0\4\12\224\0\3\12\273\0\125\12\1\0\107\12"+
    "\1\0\2\12\2\0\1\12\2\0\2\12\2\0\4\12"+
    "\1\0\14\12\1\0\1\12\1\0\7\12\1\0\101\12"+
    "\1\0\4\12\2\0\10\12\1\0\7\12\1\0\34\12"+
    "\1\0\4\12\1\0\5\12\1\0\1\12\3\0\7\12"+
    "\1\0\u0154\12\2\0\31\12\1\0\31\12\1\0\37\12"+
    "\1\0\31\12\1\0\37\12\1\0\31\12\1\0\37\12"+
    "\1\0\31\12\1\0\37\12\1\0\31\12\1\0\10\12"+
    "\2\0\62\27\67\12\4\0\62\12\10\0\1\12\16\0"+
    "\1\12\26\0\5\12\1\0\17\12\120\0\7\12\1\0"+
    "\21\12\2\0\7\12\1\0\2\12\1\0\5\12\325\0"+
    "\55\12\3\0\16\12\2\0\12\27\4\0\1\12\u0171\0"+
    "\60\12\12\27\6\0\305\12\13\0\7\12\51\0\114\12"+
    "\4\0\12\27\246\0\4\12\1\0\33\12\1\0\2\12"+
    "\1\0\1\12\2\0\1\12\1\0\12\12\1\0\4\12"+
    "\1\0\1\12\1\0\1\12\6\0\1\12\4\0\1\12"+
    "\1\0\1\12\1\0\1\12\1\0\3\12\1\0\2\12"+
    "\1\0\1\12\2\0\1\12\1\0\1\12\1\0\1\12"+
    "\1\0\1\12\1\0\1\12\1\0\2\12\1\0\1\12"+
    "\2\0\4\12\1\0\7\12\1\0\4\12\1\0\4\12"+
    "\1\0\1\12\1\0\12\12\1\0\21\12\5\0\3\12"+
    "\1\0\5\12\1\0\21\12\164\0\32\12\6\0\32\12"+
    "\6\0\32\12\166\0\327\12\51\0\65\12\13\0\336\12"+
    "\2\0\u0182\12\16\0\u0131\12\37\0\36\12\342\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[29440];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\2\2\1\3\1\4\2\5\1\6\3\7"+
    "\1\10\1\11\1\10\1\12\4\7\1\13\10\7\1\14"+
    "\3\7\1\15\1\16";

  private static int [] zzUnpackAction() {
    int [] result = new int[36];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\30\0\60\0\60\0\110\0\60\0\60\0\60"+
    "\0\140\0\170\0\220\0\250\0\300\0\60\0\60\0\330"+
    "\0\60\0\60\0\360\0\u0108\0\u0120\0\60\0\u0138\0\u0150"+
    "\0\u0168\0\u0180\0\u0198\0\u01b0\0\u01c8\0\u01e0\0\220\0\u01f8"+
    "\0\u0210\0\u0228\0\220\0\220";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[36];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\2\4\1\5\1\6\1\7\1\10\1\11\1\12"+
    "\1\3\1\13\1\3\1\14\1\15\11\13\1\3\4\16"+
    "\1\17\6\16\1\20\14\16\32\0\1\4\33\0\2\11"+
    "\30\0\1\21\25\0\2\13\1\0\1\22\1\13\1\0"+
    "\14\13\6\0\2\13\1\0\1\22\1\13\1\0\1\13"+
    "\1\23\12\13\6\0\2\13\1\0\1\22\1\13\1\0"+
    "\7\13\1\24\1\25\3\13\4\0\1\26\31\0\2\13"+
    "\1\0\1\22\1\13\1\0\11\13\1\27\2\13\6\0"+
    "\2\13\1\0\1\22\1\13\1\0\7\13\1\30\4\13"+
    "\6\0\2\13\1\0\1\22\1\13\1\0\3\13\1\31"+
    "\10\13\6\0\2\13\1\0\1\22\1\13\1\0\12\13"+
    "\1\32\1\13\6\0\2\13\1\0\1\22\1\13\1\0"+
    "\5\13\1\33\6\13\6\0\2\13\1\0\1\22\1\13"+
    "\1\0\1\34\13\13\6\0\2\13\1\0\1\22\1\13"+
    "\1\0\10\13\1\35\3\13\6\0\2\13\1\0\1\22"+
    "\1\13\1\0\3\13\1\36\10\13\6\0\2\13\1\0"+
    "\1\22\1\13\1\0\4\13\1\37\7\13\6\0\2\13"+
    "\1\0\1\22\1\13\1\0\1\40\13\13\6\0\2\13"+
    "\1\0\1\22\1\13\1\0\1\41\13\13\6\0\2\13"+
    "\1\0\1\22\1\13\1\0\2\13\1\42\11\13\6\0"+
    "\2\13\1\0\1\22\1\13\1\0\6\13\1\43\5\13"+
    "\6\0\2\13\1\0\1\22\1\13\1\0\12\13\1\44"+
    "\1\13";

  private static int [] zzUnpackTrans() {
    int [] result = new int[576];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\2\11\1\1\3\11\5\1\2\11\1\1\2\11"+
    "\3\1\1\11\16\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[36];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    /*************************************************************************
    * En esta sección se puede incluir código que se copiará textualmente
    * como parte de la definición de la clase del analizador léxico.
    * Típicamente serán variables de instancia o nuevos métodos de la clase.
    *************************************************************************/

    int string_yyline = 0;
    int string_yycolumn = 0;

    StringBuffer string = new StringBuffer();

    private MiToken token(String nombre) {
        return new MiToken(nombre, this.yyline, this.yycolumn);
    }

    private MiToken token(String nombre, Object valor) {
        return new MiToken(nombre, this.yyline, this.yycolumn, valor);
    }

    private MiToken token(String nombre, int line, int column, Object valor) {
        return new MiToken(nombre, line, column, valor);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public MiLexico(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public MiToken yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { throw new Error("Illegal character <"+yytext()+">");
            }
            // fall through
          case 15: break;
          case 2:
            { /* ignore */
            }
            // fall through
          case 16: break;
          case 3:
            { string.setLength(0); 
                                    yybegin(STRING); 
                                    string_yyline = this.yyline;
                                    string_yycolumn = this.yycolumn;
            }
            // fall through
          case 17: break;
          case 4:
            { return token("PLUS", yytext());
            }
            // fall through
          case 18: break;
          case 5:
            { return token("INTEGER_LITERAL", yytext());
            }
            // fall through
          case 19: break;
          case 6:
            { return token("EQ", yytext());
            }
            // fall through
          case 20: break;
          case 7:
            { return token("IDENTIFIER", yytext());
            }
            // fall through
          case 21: break;
          case 8:
            { string.append( yytext() );
            }
            // fall through
          case 22: break;
          case 9:
            { yybegin(YYINITIAL);
                                   return token("STRING_LITERAL", string_yyline, string_yycolumn, string.toString());
            }
            // fall through
          case 23: break;
          case 10:
            { return token("EQEQ", yytext());
            }
            // fall through
          case 24: break;
          case 11:
            { string.append('\"');
            }
            // fall through
          case 25: break;
          case 12:
            { return token("BREAK", yytext());
            }
            // fall through
          case 26: break;
          case 13:
            { return token("BOOLEAN", yytext());
            }
            // fall through
          case 27: break;
          case 14:
            { return token("ABSTRACT", yytext());
            }
            // fall through
          case 28: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
